package competitionsys.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author Michael
 */
public class Eliminations extends javax.swing.JPanel {

    /**
     * Creates new form Eliminations
     */
    public Eliminations() {
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g) {
        Image dbImg = createImage(getWidth(), getHeight());
        Graphics dbg = dbImg.getGraphics();
        draw(dbg);
        g.drawImage(dbImg, 0, 0, this);
    }

    public void draw(Graphics g) {
        g.setColor(Color.white);
        for (int i = 20; i < 360; i += 100) {
            g.drawRect(20, i, 200, 40);
            g.drawRect(20, i + 40, 200, 40);
        }
        for (int i = 70; i < 330; i += 200) {
            g.drawRect(240, i, 200, 40);
            g.drawRect(240, i + 40, 200, 40);
        }
        g.drawRect(460, 170, 200, 40);
        g.drawRect(460, 210, 200, 40);
//        g.drawRect(20, 20, 200, 40);
//        g.drawRect(20, 60, 200, 40);
//        g.drawRect(20, 120, 200, 40);
//        g.drawRect(20, 160, 200, 40);
//        g.drawRect(20, 220, 200, 40);
//        g.drawRect(20, 260, 200, 40);
//        g.drawRect(20, 320, 200, 40);
//        g.drawRect(20, 360, 200, 40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
