package competitionsys.gui.cards;

import competitionsys.gui.GUICard;

/**
 *
 * @author Michael
 */
public class MainHolder extends javax.swing.JPanel implements GUICard {

    /** Creates new form Main */
    public MainHolder() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new competitionsys.gui.cards.Main();

        setBackground(new java.awt.Color(255, 0, 0));
        setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1680, 1050));
        setMinimumSize(new java.awt.Dimension(1680, 1050));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 1660, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private competitionsys.gui.cards.Main main;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
        main.init();
    }

    @Override
    public void close() {
        main.close();
    }

    @Override
    public void nowVisible() {
        main.nowVisible();
    }

    @Override
    public void nowHidden() {
        main.nowHidden();
    }

}
