package competitionsys.gui.tabs;

import competitionsys.gui.*;
import competitionsys.persistence.Match;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author Michael
 */
public class MatchScheduleLabels2 extends javax.swing.JPanel {

    JLabel[] labels;

    /**
     * Creates new form MatchScheduleRow
     */
    public MatchScheduleLabels2() {
        initComponents();
        labels = new JLabel[9];
        labels[0] = matchNumber;
        labels[1] = blue1;
        labels[2] = blue2;
        labels[3] = blue3;
        labels[4] = red1;
        labels[5] = red2;
        labels[6] = red3;
        labels[7] = battery;
        labels[8] = time;
    }

    public void setLabels(int match, int blue1, int blue2, int blue3, int red1,
            int red2, int red3, String battery, String time) {
        matchNumber.setText(String.valueOf(match));
        this.blue1.setText(String.valueOf(blue1));
        this.blue2.setText(String.valueOf(blue2));
        this.blue3.setText(String.valueOf(blue3));
        this.red1.setText(String.valueOf(red1));
        this.red2.setText(String.valueOf(red2));
        this.red3.setText(String.valueOf(red3));
        this.battery.setText(battery);
        this.time.setText(time);
        checkColors();
    }
    
    public void setLabels(Match match) {
        setLabels(match.getMatchNumber(), match.getBlueStation1(),
                match.getBlueStation2(), match.getBlueStation3(),
                match.getRedStation1(), match.getRedStation2(),
                match.getRedStation3(), match.getBatteryLetter(),
                match.getMatchTime());
    }

    public void setLabelsBlank() {
        matchNumber.setText("");
        this.blue1.setText("");
        this.blue2.setText("");
        this.blue3.setText("");
        this.red1.setText("");
        this.red2.setText("");
        this.red3.setText("");
        this.battery.setText("");
        this.time.setText("");
        checkColors();
    }

    private void checkColors() {
        for (int i = 1; i < 7; i++) {
            switch (labels[i].getText()) {
                case "2771":
                    labels[i].setBackground(Color.DARK_GRAY);
                    break;
                case "":
                    labels[i].setBackground(Color.BLACK);
                    break;
                default:
                    if (i < 4) {
                        labels[i].setBackground(Color.BLUE);
                    } else {
                        labels[i].setBackground(Color.RED);
                    }   break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blue1 = new javax.swing.JLabel();
        matchNumber = new javax.swing.JLabel();
        blue2 = new javax.swing.JLabel();
        blue3 = new javax.swing.JLabel();
        red1 = new javax.swing.JLabel();
        red2 = new javax.swing.JLabel();
        red3 = new javax.swing.JLabel();
        battery = new javax.swing.JLabel();
        time = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        blue1.setBackground(new java.awt.Color(0, 0, 255));
        blue1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blue1.setForeground(new java.awt.Color(255, 255, 255));
        blue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blue1.setToolTipText("");
        blue1.setOpaque(true);
        blue1.setMinimumSize(new Dimension(51, 14));
        blue1.setMaximumSize(new Dimension(51, 14));

        matchNumber.setBackground(new java.awt.Color(0, 0, 0));
        matchNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        matchNumber.setForeground(new java.awt.Color(255, 255, 255));
        matchNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        matchNumber.setOpaque(true);
        matchNumber.setMinimumSize(new Dimension(9, 14));
        matchNumber.setMaximumSize(new Dimension(9, 14));

        blue2.setBackground(new java.awt.Color(0, 0, 255));
        blue2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blue2.setForeground(new java.awt.Color(255, 255, 255));
        blue2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blue2.setToolTipText("");
        blue2.setOpaque(true);
        blue2.setMinimumSize(new Dimension(51, 14));
        blue2.setMaximumSize(new Dimension(51, 14));

        blue3.setBackground(new java.awt.Color(0, 0, 255));
        blue3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blue3.setForeground(new java.awt.Color(255, 255, 255));
        blue3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blue3.setToolTipText("");
        blue3.setOpaque(true);
        blue3.setMinimumSize(new Dimension(51, 14));
        blue3.setMaximumSize(new Dimension(51, 14));

        red1.setBackground(new java.awt.Color(255, 0, 0));
        red1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        red1.setForeground(new java.awt.Color(255, 255, 255));
        red1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        red1.setToolTipText("");
        red1.setOpaque(true);
        red1.setMinimumSize(new Dimension(51, 14));
        red1.setMaximumSize(new Dimension(51, 14));

        red2.setBackground(new java.awt.Color(255, 0, 0));
        red2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        red2.setForeground(new java.awt.Color(255, 255, 255));
        red2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        red2.setToolTipText("");
        red2.setOpaque(true);
        red2.setMinimumSize(new Dimension(51, 14));
        red2.setMaximumSize(new Dimension(51, 14));

        red3.setBackground(new java.awt.Color(255, 0, 0));
        red3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        red3.setForeground(new java.awt.Color(255, 255, 255));
        red3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        red3.setToolTipText("");
        red3.setOpaque(true);
        red3.setMinimumSize(new Dimension(51, 14));
        red3.setMaximumSize(new Dimension(51, 14));

        battery.setBackground(new java.awt.Color(0, 0, 0));
        battery.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        battery.setForeground(new java.awt.Color(255, 255, 255));
        battery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        battery.setOpaque(true);
        battery.setMinimumSize(new Dimension(43, 14));
        battery.setMaximumSize(new Dimension(43, 14));

        time.setBackground(new java.awt.Color(0, 0, 0));
        time.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setToolTipText("");
        time.setOpaque(true);
        time.setMinimumSize(new Dimension(51, 14));
        time.setMaximumSize(new Dimension(51, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(matchNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blue1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(blue2)
                .addGap(18, 18, 18)
                .addComponent(blue3)
                .addGap(18, 18, 18)
                .addComponent(red1)
                .addGap(18, 18, 18)
                .addComponent(red2)
                .addGap(18, 18, 18)
                .addComponent(red3)
                .addGap(18, 18, 18)
                .addComponent(battery)
                .addGap(18, 18, 18)
                .addComponent(time)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(blue1)
                .addComponent(blue2)
                .addComponent(blue3)
                .addComponent(red1)
                .addComponent(red2)
                .addComponent(red3)
                .addComponent(battery)
                .addComponent(time)
                .addComponent(matchNumber))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel battery;
    private javax.swing.JLabel blue1;
    private javax.swing.JLabel blue2;
    private javax.swing.JLabel blue3;
    private javax.swing.JLabel matchNumber;
    private javax.swing.JLabel red1;
    private javax.swing.JLabel red2;
    private javax.swing.JLabel red3;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

}
