package competitionsys.gui.cards.startup;

/**
 *
 * @author Michael
 */
public class ScrapeInfo extends javax.swing.JPanel {

    private MainStartupCard main;

    /**
     * Creates new form LoadCompetition
     */
    public ScrapeInfo() {
        initComponents();
    }

    public void init(MainStartupCard main) {
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codeRedLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        skip = new javax.swing.JButton();
        url = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        scrape = new javax.swing.JButton();

        setBackground(new java.awt.Color(41, 41, 41));

        codeRedLogo.setBackground(new java.awt.Color(255, 255, 255));
        codeRedLogo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        codeRedLogo.setForeground(new java.awt.Color(255, 255, 255));
        codeRedLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codeRedLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/competitionsys/gui/mediumcodered.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Setup a new competition by downloading data:");

        skip.setBackground(new java.awt.Color(41, 41, 41));
        skip.setForeground(new java.awt.Color(255, 255, 255));
        skip.setText("SKIP ---->");
        skip.setFocusable(false);
        skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipActionPerformed(evt);
            }
        });

        url.setBackground(new java.awt.Color(41, 41, 41));
        url.setForeground(new java.awt.Color(254, 254, 254));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("URL:");

        scrape.setBackground(new java.awt.Color(41, 41, 41));
        scrape.setForeground(new java.awt.Color(255, 255, 255));
        scrape.setText("Download Data");
        scrape.setFocusable(false);
        scrape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(codeRedLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1680, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(skip)
                .addContainerGap())
            .addComponent(url)
            .addComponent(scrape, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(codeRedLogo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrape)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                .addComponent(skip)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scrapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrapeActionPerformed
        main.scrapeInfo(url.getText());
    }//GEN-LAST:event_scrapeActionPerformed

    private void skipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipActionPerformed
        main.skipScrapeInfo();
    }//GEN-LAST:event_skipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codeRedLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton scrape;
    private javax.swing.JButton skip;
    private javax.swing.JTextField url;
    // End of variables declaration//GEN-END:variables

}
